In [1]:
import pandas as pd

In [4]:
# reading the csv file
df_exams = pd.read_csv('StudentsPerformance.csv')
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

#**Create Index**

In [5]:
import numpy as np
import random

In [8]:
# creating non repetitive values for the index
new_index = np.arange(0,1000)
new_index

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181,
       182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194,
       195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207,
       208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220,
       221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233,
       234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246,
       247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259,
       260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272,
       273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285,
       286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298,
       299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311,
       312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324,
       325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337,
       338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350,
       351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363,
       364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376,
       377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389,
       390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402,
       403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415,
       416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428,
       429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441,
       442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454,
       455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467,
       468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480,
       481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493,
       494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506,
       507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519,
       520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532,
       533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545,
       546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558,
       559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571,
       572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584,
       585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597,
       598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610,
       611, 612, 613, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623,
       624, 625, 626, 627, 628, 629, 630, 631, 632, 633, 634, 635, 636,
       637, 638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649,
       650, 651, 652, 653, 654, 655, 656, 657, 658, 659, 660, 661, 662,
       663, 664, 665, 666, 667, 668, 669, 670, 671, 672, 673, 674, 675,
       676, 677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687, 688,
       689, 690, 691, 692, 693, 694, 695, 696, 697, 698, 699, 700, 701,
       702, 703, 704, 705, 706, 707, 708, 709, 710, 711, 712, 713, 714,
       715, 716, 717, 718, 719, 720, 721, 722, 723, 724, 725, 726, 727,
       728, 729, 730, 731, 732, 733, 734, 735, 736, 737, 738, 739, 740,
       741, 742, 743, 744, 745, 746, 747, 748, 749, 750, 751, 752, 753,
       754, 755, 756, 757, 758, 759, 760, 761, 762, 763, 764, 765, 766,
       767, 768, 769, 770, 771, 772, 773, 774, 775, 776, 777, 778, 779,
       780, 781, 782, 783, 784, 785, 786, 787, 788, 789, 790, 791, 792,
       793, 794, 795, 796, 797, 798, 799, 800, 801, 802, 803, 804, 805,
       806, 807, 808, 809, 810, 811, 812, 813, 814, 815, 816, 817, 818,
       819, 820, 821, 822, 823, 824, 825, 826, 827, 828, 829, 830, 831,
       832, 833, 834, 835, 836, 837, 838, 839, 840, 841, 842, 843, 844,
       845, 846, 847, 848, 849, 850, 851, 852, 853, 854, 855, 856, 857,
       858, 859, 860, 861, 862, 863, 864, 865, 866, 867, 868, 869, 870,
       871, 872, 873, 874, 875, 876, 877, 878, 879, 880, 881, 882, 883,
       884, 885, 886, 887, 888, 889, 890, 891, 892, 893, 894, 895, 896,
       897, 898, 899, 900, 901, 902, 903, 904, 905, 906, 907, 908, 909,
       910, 911, 912, 913, 914, 915, 916, 917, 918, 919, 920, 921, 922,
       923, 924, 925, 926, 927, 928, 929, 930, 931, 932, 933, 934, 935,
       936, 937, 938, 939, 940, 941, 942, 943, 944, 945, 946, 947, 948,
       949, 950, 951, 952, 953, 954, 955, 956, 957, 958, 959, 960, 961,
       962, 963, 964, 965, 966, 967, 968, 969, 970, 971, 972, 973, 974,
       975, 976, 977, 978, 979, 980, 981, 982, 983, 984, 985, 986, 987,
       988, 989, 990, 991, 992, 993, 994, 995, 996, 997, 998, 999])

In [10]:
# shuffling the indexes
random.shuffle(new_index)
new_index

array([168, 160, 549, 539, 696, 116, 462, 602, 771, 728, 739, 106, 944,
       482,  37, 624, 571, 478, 221,   6, 248, 275, 111, 825, 660, 231,
         1, 874, 423, 458, 963, 906, 600, 650, 974, 843, 917,  69, 124,
       848, 138, 621,  34, 814, 261, 466, 960, 904, 939, 467, 465, 899,
       290, 398, 787, 298, 540,  39, 577, 722, 499, 987, 429, 370, 147,
       973, 907, 283, 219,  23, 751, 212, 339, 979, 841, 392, 674, 154,
       975, 115, 238, 265, 845, 256, 360, 439, 197, 651, 806, 292, 299,
       645, 375,  20, 311, 971,  73, 593, 873, 972, 126, 333, 633, 194,
       812,  80, 895, 446, 441, 543, 306, 886, 793, 596, 584, 176,  38,
       166,  15, 714, 200, 754,  31,  93, 460, 989, 517, 941, 420, 323,
       547, 378, 245, 618, 497, 397,  81,  32, 635, 114, 664, 753, 225,
       760, 994,  59, 464, 682, 514, 574, 132, 925, 638, 933, 969, 870,
       747, 786, 998, 512, 148,  17, 649,  63, 416, 101, 230, 992, 227,
       831, 914, 293, 705, 888, 686, 436, 141, 860, 646, 504, 881, 180,
       918, 791, 328, 411, 690, 344, 528, 700, 505, 849, 334, 792, 412,
       614, 773,  57, 318, 768, 273,   3, 573, 928, 896, 585,  42, 756,
       707, 393, 932, 993, 669, 763, 302, 217, 653, 519, 295, 832, 731,
        78, 234, 765,  54, 277, 342, 172, 676, 611, 507, 493, 541, 191,
       242, 379, 632, 356, 167,  72,  22, 448, 380, 822, 297,  92, 366,
       887, 183, 681, 409, 450, 195, 169, 659, 604, 222, 856, 702, 957,
       855, 174, 506, 352, 253,  16, 589, 755, 313, 110, 307, 502, 665,
       807, 699, 834, 764, 492, 775, 984, 796, 287,  91, 759, 996, 214,
       435, 730, 910, 655, 835, 813, 432,  14, 922, 305, 713, 181, 134,
       542, 846, 402, 209,  67, 223, 350, 615, 389, 704, 622, 694, 425,
       844, 930, 377, 892, 563, 373, 424,  99, 120, 670, 210, 321, 976,
       445, 286, 777, 471,  29, 250, 916, 620, 840, 175, 721, 203, 246,
       798, 903, 498, 417, 970, 369,  83, 434, 749, 570, 510, 847, 951,
       866, 647, 264, 947, 187, 797, 382, 149, 923, 335, 188, 479, 872,
       278, 457, 358, 271, 531, 348, 240, 428, 414, 977, 308, 500, 453,
       178, 879, 641,   8, 485, 752, 556, 830,  53, 607, 536, 319, 249,
       345, 349, 703, 513, 443, 767, 758,  94, 391, 207, 867, 190, 269,
       688, 811, 980, 347, 673, 475, 327, 828, 946, 626, 388, 300,  65,
       112, 396, 601, 523, 658,  95, 956, 795, 255, 534, 929,   4, 672,
       643, 550, 150, 595, 480, 781,  44,  68, 208, 524, 384, 882, 942,
       770, 572, 691, 816, 545, 362, 575,   7, 533, 981, 555, 394, 456,
        89, 819, 156, 309, 750, 232, 943, 501, 965,   0, 689, 627,  49,
       267, 861, 898, 102, 920, 196, 909, 538, 897, 239,  50, 636, 291,
       433,  60, 316, 201, 170, 725, 405, 640, 912, 983, 823, 236, 281,
       182,  87, 788, 304, 430, 737, 726,  36, 808, 718, 337, 107, 186,
       708, 966, 805, 109, 400, 266, 529, 683, 359, 158,  85, 228, 164,
       876, 476, 732, 104, 372, 361, 406, 740, 927, 520, 544, 426, 619,
       322, 783, 644, 815, 919, 687, 130, 133, 477, 566, 251, 709, 757,
       276, 368, 858, 809, 842, 522, 729, 330, 829, 314, 826,  64, 202,
       710,  30, 934, 211,  43, 161, 893, 668,   2, 491, 125, 263, 838,
        98, 552, 431, 454, 988, 371, 329, 961, 179, 661, 385, 153, 455,
       422, 959, 470,  66, 374, 495, 199, 937, 152,  51, 580, 162, 868,
       351, 140, 801, 135, 657, 784, 851, 216, 695, 706, 678, 817, 224,
       437, 833, 776, 734, 864, 558, 671, 427,  77, 782, 122, 576,  25,
       642, 442, 521, 341, 461, 890, 656, 712, 119, 908, 820, 591, 862,
       634, 105, 546, 100, 103, 964,  52, 837, 376, 254, 252, 613, 399,
        55, 738,   9, 303,  56, 320, 282, 839, 854, 215, 289, 274, 724,
       684, 736, 623, 779, 772, 581, 171, 911, 142, 447, 953, 173, 518,
       803,  41, 325, 338, 711, 260, 985, 617, 486, 516, 503, 597, 883,
       612, 508, 802, 386, 629, 962,  58,  90, 692, 719, 924, 594, 288,
       146, 357, 821, 562, 863, 488, 241, 127, 850, 548, 294, 774, 410,
       537, 483, 810, 317,  40, 560, 415, 762, 218,  84,  47, 487,  45,
       679, 999,   5,  70, 474,  21, 905, 598, 551,  28, 606, 875, 258,
       583, 666, 742,  74, 744, 799, 746, 785, 554,  48, 143, 192, 900,
       527, 257, 419, 720, 616, 151, 408, 952,  61, 193, 387, 986, 526,
       489,  24, 557, 717, 836, 675, 913, 891,  33, 685, 463,  13, 778,
       878, 680, 118, 997, 383, 967, 452, 401, 877, 494, 363, 496, 592,
       978, 982, 312,  35, 894, 165, 364, 403, 525, 991, 884, 954, 131,
       459, 857, 693, 237, 413, 324, 301, 818, 628, 468, 800, 701, 532,
       586, 631, 343,  82, 559, 407, 990,  12, 652, 185, 184, 940, 296,
       451, 902,  86, 395,  27, 418, 189, 473, 921, 853, 950, 535,  96,
       117, 745, 955, 561, 390, 157, 654, 284, 639, 243, 608, 108, 440,
       698, 625, 163, 332, 247, 599,  71, 206, 128, 279, 569, 336, 789,
        19,  75, 472, 229, 331, 889, 935, 715, 564, 220, 824, 648, 159,
       204, 326, 511, 145, 630, 697, 741, 404, 766, 603, 121, 268, 663,
       579, 367, 780, 340, 605, 139, 509, 869, 280, 310, 587, 565, 481,
       610,  10, 761, 155, 568, 262,  18, 743, 144, 205, 270, 794, 948,
       490, 582, 949, 235, 259, 484, 804, 315, 177, 667, 637, 198,  11,
       213, 901, 865, 936, 968, 567, 735, 727, 609, 469, 381, 748, 355,
       915, 588, 995, 859, 880, 931, 449, 346,  76, 113, 353, 272,  46,
       129,  97, 827, 137, 852, 723, 421, 885, 578, 444, 677, 438, 553,
       926, 938, 958, 733, 123, 136,  88, 226, 945, 365, 354, 871, 244,
        79, 515, 769, 790,  26, 530, 590, 285,  62, 233, 662, 716])

In [11]:
# create a new column with new index
df_exams['new_index'] = new_index
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,new_index
0,female,group B,bachelor's degree,standard,none,72,72,74,168
1,female,group C,some college,standard,completed,69,90,88,160
2,female,group B,master's degree,standard,none,90,95,93,549
3,male,group A,associate's degree,free/reduced,none,47,57,44,539
4,male,group C,some college,standard,none,76,78,75,696
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,285
996,male,group C,high school,free/reduced,none,62,55,55,62
997,female,group C,high school,free/reduced,completed,59,71,65,233
998,female,group D,some college,standard,completed,68,78,77,662
999,female,group D,some college,free/reduced,none,77,86,86,716

#**Set Index**

In [13]:
# set new_index column as index
df_exams.set_index('new_index',inplace=True)
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
new_index,,,,,,,,
168,female,group B,bachelor's degree,standard,none,72,72,74
160,female,group C,some college,standard,completed,69,90,88
549,female,group B,master's degree,standard,none,90,95,93
539,male,group A,associate's degree,free/reduced,none,47,57,44
696,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
285,female,group E,master's degree,standard,completed,88,99,95
62,male,group C,high school,free/reduced,none,62,55,55
233,female,group C,high school,free/reduced,completed,59,71,65
662,female,group D,some college,standard,completed,68,78,77
716,female,group D,some college,free/reduced,none,77,86,86

#**Sort Index**

In [14]:
# sort dataframe by new index
df_exams.sort_index()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
new_index,,,,,,,,
0,male,group A,bachelor's degree,standard,completed,75,58,62
1,male,group B,some college,standard,none,69,54,55
2,female,group D,master's degree,free/reduced,completed,61,71,78
3,female,group D,some college,free/reduced,none,65,81,77
4,male,group C,some high school,free/reduced,none,69,71,65
...,...,...,...,...,...,...,...,...
995,female,group D,some college,standard,completed,75,77,83
996,female,group B,some high school,standard,none,37,46,46
997,female,group C,associate's degree,standard,completed,52,59,62
998,female,group B,associate's degree,standard,completed,61,86,87
999,male,group C,some college,standard,none,53,39,37

In [15]:
# sort descending by index
df_exams.sort_index(ascending=False)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
new_index,,,,,,,,
999,male,group C,some college,standard,none,53,39,37
998,female,group B,associate's degree,standard,completed,61,86,87
997,female,group C,associate's degree,standard,completed,52,59,62
996,female,group B,some high school,standard,none,37,46,46
995,female,group D,some college,standard,completed,75,77,83
...,...,...,...,...,...,...,...,...
4,male,group C,some high school,free/reduced,none,69,71,65
3,female,group D,some college,free/reduced,none,65,81,77
2,female,group D,master's degree,free/reduced,completed,61,71,78
1,male,group B,some college,standard,none,69,54,55
0,male,group A,bachelor's degree,standard,completed,75,58,62