In [1]:
import pandas as pd

#**Read a .csv from a URL with Pandas**

target website : [https://www.football-data.co.uk/data.php](https://www.football-data.co.uk/data.php)

In [10]:
# reading 1 csv file from the website
df_premier21 = pd.read_csv('https://www.football-data.co.uk/mmz4281/2425/E0.csv')

In [11]:
# showing dataframe
df_premier21

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,16/08/2024,20:00,Man United,Fulham,1,0,H,0,0,...,1.86,2.07,1.83,2.11,1.88,2.11,1.82,2.05,1.90,2.08
1,E0,17/08/2024,12:30,Ipswich,Liverpool,0,2,A,0,0,...,2.05,1.88,2.04,1.90,2.20,2.00,1.99,1.88,2.04,1.93
2,E0,17/08/2024,15:00,Arsenal,Wolves,2,0,H,1,0,...,2.02,1.91,2.00,1.90,2.05,1.93,1.99,1.87,2.02,1.96
3,E0,17/08/2024,15:00,Everton,Brighton,0,3,A,0,1,...,1.87,2.06,1.86,2.07,1.92,2.10,1.83,2.04,1.88,2.11
4,E0,17/08/2024,15:00,Newcastle,Southampton,1,0,H,1,0,...,1.87,2.06,1.88,2.06,1.89,2.10,1.82,2.05,1.89,2.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,25/05/2025,16:00,Newcastle,Everton,0,1,A,0,0,...,2.00,1.85,2.01,1.90,2.01,1.95,1.95,1.91,1.93,2.05
376,E0,25/05/2025,16:00,Nott'm Forest,Chelsea,0,1,A,0,0,...,1.80,2.05,1.86,2.08,1.86,2.08,1.81,2.05,1.86,2.14
377,E0,25/05/2025,16:00,Southampton,Arsenal,1,2,A,0,1,...,2.03,1.83,2.04,1.87,2.07,1.87,2.03,1.83,2.06,1.89
378,E0,25/05/2025,16:00,Tottenham,Brighton,1,4,A,1,0,...,1.95,1.90,2.00,1.93,2.01,1.93,1.95,1.89,2.06,1.93
379,E0,25/05/2025,16:00,Wolves,Brentford,1,1,D,0,1,...,1.85,2.00,1.90,2.03,1.90,2.05,1.85,1.97,1.89,2.10

In [12]:
# rename columns
df_premier21.rename(columns={'FTHG':'Home_Goals',
                             'FTAG':'Away_Goals'},inplace=True)

In [13]:
#show the dataframe
df_premier21

,Div,Date,Time,HomeTeam,AwayTeam,Home_Goals,Away_Goals,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,16/08/2024,20:00,Man United,Fulham,1,0,H,0,0,...,1.86,2.07,1.83,2.11,1.88,2.11,1.82,2.05,1.90,2.08
1,E0,17/08/2024,12:30,Ipswich,Liverpool,0,2,A,0,0,...,2.05,1.88,2.04,1.90,2.20,2.00,1.99,1.88,2.04,1.93
2,E0,17/08/2024,15:00,Arsenal,Wolves,2,0,H,1,0,...,2.02,1.91,2.00,1.90,2.05,1.93,1.99,1.87,2.02,1.96
3,E0,17/08/2024,15:00,Everton,Brighton,0,3,A,0,1,...,1.87,2.06,1.86,2.07,1.92,2.10,1.83,2.04,1.88,2.11
4,E0,17/08/2024,15:00,Newcastle,Southampton,1,0,H,1,0,...,1.87,2.06,1.88,2.06,1.89,2.10,1.82,2.05,1.89,2.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,25/05/2025,16:00,Newcastle,Everton,0,1,A,0,0,...,2.00,1.85,2.01,1.90,2.01,1.95,1.95,1.91,1.93,2.05
376,E0,25/05/2025,16:00,Nott'm Forest,Chelsea,0,1,A,0,0,...,1.80,2.05,1.86,2.08,1.86,2.08,1.81,2.05,1.86,2.14
377,E0,25/05/2025,16:00,Southampton,Arsenal,1,2,A,0,1,...,2.03,1.83,2.04,1.87,2.07,1.87,2.03,1.83,2.06,1.89
378,E0,25/05/2025,16:00,Tottenham,Brighton,1,4,A,1,0,...,1.95,1.90,2.00,1.93,2.01,1.93,1.95,1.89,2.06,1.93
379,E0,25/05/2025,16:00,Wolves,Brentford,1,1,D,0,1,...,1.85,2.00,1.90,2.03,1.90,2.05,1.85,1.97,1.89,2.10

#**Read .csv from Multiple URLs with Pandas**

https://www.football-data.co.uk/mmz4281/2122/E0.csv

**Link : Root + season + league**

In [8]:
#link structure
"https://www.football-data.co.uk/mmz4281/" + "2122" + "/" + "E0" + ".csv"

'https://www.football-data.co.uk/mmz4281/2122/E0.csv'

In [9]:
# create a root variable
root = "https://www.football-data.co.uk/mmz4281/"

#Multiple leagues



*   https://www.football-data.co.uk/mmz4281/2122/E0.csv

*   https://www.football-data.co.uk/mmz4281/2122/E1.csv

*   https://www.football-data.co.uk/mmz4281/2122/E2.csv
*   https://www.football-data.co.uk/mmz4281/2122/E3.csv

*   https://www.football-data.co.uk/mmz4281/2122/EC.csv

In [17]:
from __future__ import unicode_literals
#creating list of the leagues
leagues =['E0','E1','E2','E3','EC']
# to store all the datafrane
frames = []
#loop through leagues, read multiple csv and append it into the list
for league in leagues:
  df = pd.read_csv(root + '2122' + '/' +league + '.csv',encoding='unicode_escape')
  frames.append(df)

In [20]:
#length of the frames
len(frames)

5

In [22]:
# show 1st, 2nd and 3rd element
frames[2].head(3)

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E2,07/08/2021,15:00,Bolton,Milton Keynes Dons,3,3,D,1,1,...,1.97,-0.25,1.90,1.95,1.91,1.97,1.99,2.01,1.90,1.92
1,E2,07/08/2021,15:00,Cambridge,Oxford,1,1,D,0,1,...,1.86,0.25,2.08,1.73,2.12,1.78,2.12,1.82,2.06,1.77
2,E2,07/08/2021,15:00,Crewe,Cheltenham,1,1,D,1,1,...,1.69,-0.25,2.00,1.85,1.99,1.90,2.04,1.95,1.96,1.87

#Multiple Seasons

In [25]:
for season in range(10,25):
  print(str(season) + str(season+1))

1011
1112
1213
1314
1415
1516
1617
1718
1819
1920
2021
2122
2223
2324
2425

In [32]:
leagues = ['E0', 'E1', 'E2', 'E3', 'EC']
frames = []
# loop through range of seasons and insert new column
for league in leagues:
  for season in range(10,25):
    df=pd.read_csv(root + str(season) + str(season+1) + '/' + league + '.csv', encoding='unicode_escape')
    df.insert(1,'Season',season)
    frames.append(df)

In [36]:
# total frames (15 seasons x 5 leagues)
len(frames)

75

In [40]:
frames[48]

,Div,Season,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,BbAv<2.5,BbAH,BbAHh,BbMxAHH,BbAvAHH,BbMxAHA,BbAvAHA,PSCH,PSCD,PSCA
0,E3,13,03/08/13,Bury,Chesterfield,0,2,A,0,0,...,1.75,15.0,0.25,1.77,1.73,2.25,2.16,2.73,3.42,2.73
1,E3,13,03/08/13,Cheltenham,Burton,2,2,D,2,1,...,1.79,15.0,-0.25,1.90,1.85,2.06,2.00,2.17,3.52,3.56
2,E3,13,03/08/13,Exeter,Bristol Rvs,2,1,H,0,0,...,1.81,15.0,0.00,1.82,1.74,2.22,2.09,2.25,3.41,3.45
3,E3,13,03/08/13,Fleetwood Town,Dag and Red,3,1,H,2,1,...,1.81,16.0,-0.75,1.88,1.80,2.12,2.06,1.81,3.73,4.87
4,E3,13,03/08/13,Newport County,Accrington,4,1,H,2,0,...,1.81,16.0,-0.25,1.86,1.82,2.11,2.04,1.92,3.55,4.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
547,E3,13,03/05/14,Northampton,Oxford,3,1,H,2,1,...,1.65,20.0,-0.50,1.92,1.84,2.06,1.99,2.05,3.33,4.20
548,E3,13,03/05/14,Portsmouth,Plymouth,3,3,D,2,2,...,1.77,20.0,-0.50,2.14,2.09,1.82,1.77,2.04,3.79,3.69
549,E3,13,03/05/14,Scunthorpe,York,2,2,D,2,1,...,1.71,20.0,-0.50,2.04,1.98,1.90,1.85,2.00,3.53,4.14
550,E3,13,03/05/14,Southend,Burton,1,0,H,1,0,...,1.66,20.0,-0.25,1.90,1.79,2.14,2.05,1.90,3.61,4.51
551,E3,13,03/05/14,Torquay,Wycombe,0,3,A,0,2,...,1.67,20.0,0.25,1.83,1.79,2.11,2.05,3.01,3.42,2.51

#Organize All The Data in a Dictionary

In [41]:
# create a dictionary with original name of league as key
dict_countries = {
              'Spanish La Liga':'SP1', 'Spanish Segunda Division':'SP2',
              'German Bundesliga':'D1',
              'English Premier League':'E0', 'English League 1':'E2', 'English League 2':'E3',
             }

In [44]:
for league in dict_countries:
  print("Keys: ", league, ", values: ", dict_countries[league])

Keys:  Spanish La Liga , values:  SP1
Keys:  Spanish Segunda Division , values:  SP2
Keys:  German Bundesliga , values:  D1
Keys:  English Premier League , values:  E0
Keys:  English League 1 , values:  E2
Keys:  English League 2 , values:  E3

In [45]:
dict_historical_data = {}

# looping through key elements
for league in dict_countries:
    frames = [] # one dataframe per league
    for season in range(15, 21):
        df = pd.read_csv(root + str(season) + str(season+1) + "/" + dict_countries[league]+ ".csv")
        df.insert(1, 'season', season)
        frames.append(df)
    df_frames = pd.concat(frames) # storing all seasons of a league in a single dataframe
    dict_historical_data[league] = df_frames # assigning dataframe to a new dictionary

In [46]:
# show dataframe inside dict_historical_data
dict_historical_data['Spanish La Liga']

,Div,season,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,SP1,15,21/08/15,Malaga,Sevilla,0,0,D,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,SP1,15,22/08/15,Ath Madrid,Las Palmas,1,0,H,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,SP1,15,22/08/15,Espanol,Getafe,1,0,H,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,SP1,15,22/08/15,La Coruna,Sociedad,0,0,D,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,SP1,15,22/08/15,Vallecano,Valencia,0,0,D,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,SP1,20,22/05/2021,Osasuna,Sociedad,0,1,A,0,0,...,2.34,1.00,2.07,1.86,2.06,1.87,2.07,1.96,1.98,1.88
376,SP1,20,22/05/2021,Real Madrid,Villarreal,2,1,H,0,1,...,2.57,-1.00,2.01,1.92,2.00,1.93,2.02,2.02,1.95,1.92
377,SP1,20,22/05/2021,Valladolid,Ath Madrid,1,2,A,1,0,...,2.30,1.50,1.90,2.03,1.90,2.02,1.95,2.06,1.90,1.97
378,SP1,20,23/05/2021,Granada,Getafe,0,0,D,0,0,...,1.80,0.25,1.73,2.08,1.77,2.18,1.84,2.23,1.77,2.12
379,SP1,20,23/05/2021,Sevilla,Alaves,1,0,H,0,0,...,2.40,-1.50,1.97,1.96,1.93,1.99,2.13,2.03,1.99,1.88